#Vad behövs för projektet?

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cinema-container # Skapas en temporär databas här inne i containern.
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wigell-cinema      #databasens namn
      MYSQL_USER: keycloak         #Vart är detta inlogg?
      MYSQL_PASSWORD: password    # vart är detta inlogg?
    ports:
      - "6606:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak-wigell-cinema
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: wigell-cinema
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin             #inlogg keycloak workbench
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - mysql  #Den här 'keykcloak-cont' containern startar inte innan mysql containern startar.

  currency-converter:
    build: ./converter #varför detta? vad betyder det här? Ska denna ligga i
    ports:
      - "8587:8080"

  wigell-cinema:
    build: ./wigell-cinema
    ports:
      - "8583:8080"  # hur funkar det med portarna??

