server:
  port: 8583

info:
  app:
    name: Wigell Cinema
    version: 1.0.0

converter:
  service:
    url: http//localhost:8587

spring:
  application:
    name: wigell-cinema
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/wigell-realm

  boot: #Behövs detta stycke för att dashboard ska funka?
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin123
        instance:
          service-base-url: http://localhost:8583

  datasource:
    url: jdbc:mysql://localhost:3306/wigell_cinema_db?createDatabaseIfNotExist=true
    username: root
    password: techtjej2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true

management:
  server:
    port: 8583
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


