server:
  port: 8583

spring:
  application:
    name: wigell-cinema

  datasource:
    url: jdbc:mysql://localhost:6606/?createDatabaseIfNotExist=true
    username: root
    password: techtjej2026
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
